### PR TITLE
fix: district issue and disable

### PR DESCRIPTION
**Pull request by anand-it**
- -Remove Google/facrbook/insta icon
-  image
- Check every module to chnage select to clear
- image
- Make disbale icon 
- image
- Making Loading after to  select state
- image

### CODE REVIEW

**Comment by kumaresan-subramani** [comment]
@anand-it ,pls don't remove fb,onstand other icons
There we are going to link our links

**Comment by kural214** [comment]
@anand-it remove the white space changes

**Review by anand-it — COMMENTED** [review]
fix: remove white space

**Comment by kural214** [comment]
@anand-it 
-Remove Google/facrbook/insta icon -- I am not getting this change
image

- Check every module to chnage select to clear (add -- before and after clear)

**Comment by anand-it** [comment]
> @anand-it -Remove Google/facrbook/insta icon -- I am not getting this change image
> 
> * Check every module to chnage select to clear (add -- before and after clear)



image

**Comment by anand-it** [comment]
Check every module to chnage select to clear (add -- before and after clear) 

This Issue are Resolved in this PR https://github.com/kd-school-erp/erp-ui/pull/327

**Pull request merged**
